# Generated by Django 5.1.5 on 2025-02-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teams_delete_favoriteteams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='division',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='league',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='sport',
        ),
    ]
